# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Breadcrumb
  - trigger: ":bc"
    word: true
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo `date -v -1d \"+[[%Y-%m-%d-%a|<< Yesterday]]\"`' | '`date -v +1d \"+[[%Y-%m-%d-%a|Tomorrow >>]]\"`"

  # Meeting
  - trigger: ":meet"
    word: true
    replace: |
             ## 0000 Meeting
             - Tags/Index:
             Meeting Link:
             Attendees:
             Tasks:
             Notes:
  # Next Week
  - triggers: [ ":>nw", ":>mon" ]
    word: true
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo →  `date -v +Mon \"+[[%Y-%m-%d-%a]]\"`"

  # Quick People Notes
  - trigger: ":people"
    word: true
    replace: |
             **Title:**
             **Team:**
             **Location:**
             **Expertise:**
             **LinkedIn:**
             **Other:**

  # Steps
  - trigger: ":steps"
    word: true
    replace: "Steps to reproduce: "

  # Android
  - trigger: ":android"
    word: true
    replace: "#android (not started)"

  - trigger: ":androidi"
    word: true
    replace: "#android (in progress 🔄)"

  - trigger: ":androidc"
    word: true
    replace: "#android (complete ✅)"

  # iOS
  - trigger: ":ios"
    word: true
    replace: "#iOS (not started)"

  - trigger: ":iosi"
    word: true
    replace: "#iOS (in progress 🔄)"

  - trigger: ":iosc"
    word: true
    replace: "#iOS (complete ✅)"

  # Tool for daily notes
  - trigger: ":tool"
    word: true
    replace: "#tool (not started)"

  # Web for daily notes
  - trigger: ":web"
    word: true
    replace: "#web (not started)"

  # patrick.burdine email
  - trigger: ":pb"
    word: true
    replace: "patrick.burdine@gmail.com"

  # insert email for testing
  - trigger: ":ha"
    word: true
    replace: "patrick+{{addtime}}$|$@hallow.app"
    vars:
      - name: addtime
        type: date
        params:
          format: "%m%d%y"
 
  # insert written vs. expected for Text on Screen
  - trigger: ":writ"
    word: true
    replace: "written: $|$ actual: "

 # insert email for testing
  - trigger: ":magic"
    word: true
    replace: "https://hallow.com/magic/"
  
 # insert email for testing
  - trigger: ":bb"
    word: true
    replace: "[Security BB] "

# run command to fix audio for MacOS Tahoe
  - trigger: ":fa"
    word: true
    replace: "sudo killall coreaudiod"
