# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Breadcrumb
  - trigger: ":bc"
    word: true
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo `date -v -1d \"+[[%Y-%m-%d-%a|<< Yesterday]]\"`' | '`date -v +1d \"+[[%Y-%m-%d-%a|Tomorrow >>]]\"`"

  # Meeting
  - trigger: ":meet"
    word: true
    replace: |
             ## 0000 Meeting
             - Tags/Index: 
             Meeting Link: 
             Attendees: 
             Tasks: 
             Notes: 

  # Next Week
  - triggers: [ ":>nw", ":>mon" ]
    word: true
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo →  `date -v +Mon \"+[[%Y-%m-%d-%a]]\"`"

  # Quick People Notes
  - trigger: ":people"
    word: true
    replace: |
             **Title:** 
             **Team:**
             **Location:**
             **Expertise:**
             **LinkedIn:**
             **Other:**

  # Quick People Notes
  - trigger: ":sdet"
    word: true
    replace: "As SDET I want to $|$ so that ..."

  # Migrating Arrow for tasks
  - trigger: ":->"
    word: true
    replace: "→" 

  # Edit espanso.yml
  - trigger: ":yml"
    word: true
    replace: "vi [PATH TO YML]"

  # add php for assertSee
  - trigger: ":as"
    replace: "->assertSee('$|$')"
